In [1]:
import numpy as np

class ArrayProcessor:
    def __init__(self, bs, n, m):
        self.bs = bs  # Block size
        self.n = n    # Number of elements to retain
        self.m = m    # Length of each segment

    def process_array(self, x):
        self.x = x  # Store the array in self.x
        for i in range(len(self.x) // self.bs):  # Loop through segments of array
            l = list(self.x[i * self.bs:(i + 1) * self.bs])
            for _ in range(self.m - self.n):
                min_index = l.index(min(l))  # Find index of minimum element in l
                l[min_index] = float('inf')  # Replace the minimum element with infinity
            
            # Explicit loop to replace 'inf' with 0
            for j in range(len(l)):
                if l[j] == float('inf'):
                    l[j] = 0
            
            self.x[i * self.bs:(i + 1) * self.bs] = np.array(l)  # Update the segment of the array with modified list
        return self.x

    def process_2d_array(self, w):
        self.w = w  # Store the array in self.w
        for row in range(self.w.shape[0]):  # Loop through each row
            for i in range(self.w.shape[1] // self.bs):  # Loop through segments of the row
                l = list(self.w[row, i * self.bs:(i + 1) * self.bs])  # Slice the row into segments of length n
                for _ in range(self.m - self.n):
                    min_index = l.index(min(l))  # Find index of minimum element in l
                    l[min_index] = float('inf')  # Replace the minimum element with infinity
                
                # Explicit loop to replace 'inf' with 0
                for j in range(len(l)):
                    if l[j] == float('inf'):
                        l[j] = 0
                
                self.w[row, i * self.bs:(i + 1) * self.bs] = np.array(l)  # Update the segment of the array with modified list
        return self.w

# Example usage:
bs = 4  # Block size
n = 3  # Number of elements to retain
m = 4   # Length of each segment

x = np.array([1, 44, 2, 4, 99, 6, 9, 8])  # Input array
w = np.array([
    [1, 2, 3, 55, 5, 6, 44, 8],
    [9, 10, 11, 12, 13, 14, 15, 16],
    [17, 18, 19, 20, 21, 22, 23, 24],
    [25, 446, 27, 28, 29, 30, 31, 32],
    [2000, 34, 35, 36, 37, 38, 39, 40],
    [41, 42, 43, 44, 45, 46, 47, 48],
    [49, 50, 51, 52, 1000, 444, 55, 56],
    [57, 58, 59, 60, 61, 62, 63, 64]
])

processor = ArrayProcessor(bs, n, m)
x_processed = processor.process_array(x)
w_processed = processor.process_2d_array(w)

print(x_processed)
print(w_processed)

[ 0 44  2  4 99  0  9  8]
[[   0    2    3   55    0    6   44    8]
 [   0   10   11   12    0   14   15   16]
 [   0   18   19   20    0   22   23   24]
 [   0  446   27   28    0   30   31   32]
 [2000    0   35   36    0   38   39   40]
 [   0   42   43   44    0   46   47   48]
 [   0   50   51   52 1000  444    0   56]
 [   0   58   59   60    0   62   63   64]]
